apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - replicas.yaml  # Correct field to apply patches

configMapGenerator:
  - name: mykustom-map
    literals:
      - BG_COLOR=#000000
      - FONT_COLOR=#FFFFFF
      - CUSTOM_HEADER=Welcome to the DEV environment!!
